export const yesNo = [
  { value:'-1', text:'No' },
  { value:'1',  text:'Yes' },
];

export const titleTypes = [
  { value:'Mr',    text:'Mr' },
  { value:'Mrs',   text:'Mrs' },
  { value:'Miss',  text:'Miss' },
  { value:'Ms',    text:'Ms' },
  { value:'Dr',    text:'Dr' },       // new
  { value:'Rev',   text:'Rev' },      // new
  { value:'Other', text:'Other' }
];

export const jobTitleTypes = [
  { value:'CEO',             text:'CEO' },  // New
  { value:'Director',        text:'Director' },
  { value:'Owner',           text:'Owner' },
  { value:'Partner',         text:'Partner' },
  { value:'Secretary',       text:'Secretary' },
  { value:'Sole Proprietor', text:'Sole Proprietor' }, // New
  { value:'Treasurer',       text:'Treasurer' }, // New
  { value:'Other',           text:'Other' },
];

// export const contactTimes = [
//   { value:'1', text:'Morning' },
//   { value:'2', text:'Afternoon' },
//   { value:'3', text:'Anytime' },
// ];

export const reasonTypes = [
  { value:'3',  text:'Other purchase(s)' },
  { value:'9',  text:'Cashflow needs (< 12 months)' },
  { value:'10', text:'Other' }
];

export const representativeTypes = [
  { value:'1', text:'Main' },
  { value:'2', text:'Deputy' },
  { value:'3', text:'Neither' },
];

export const marketingTypes = [
  { value:'1', text:'Marketing via Telephone' },
  { value:'2', text:'Marketing via Post' },
  { value:'3', text:'Marketing by SMS' },
];

export const statementDateTypes = [
  { value:'1',  text:'1st-7th' },
  { value:'8',  text:'8th-14th' },
  { value:'15', text:'15th-21st' },
  { value:'22', text:'22nd-31st' },
  { value:'-1', text:'No Preference' },
];

export const deliveryTypes = [
  { value:'1',  text:'Royal mail' },
  { value:'2',  text:'Courier' },
  { value:'3',  text:'Own driver' },
  // { value:'-1',  text:'Dont Deliver Product / Service' },
];

export const repaymentTypes = [
  { value:'1', text:'100% of balance' },
  { value:'2', text:'minimum monthly' },
  { value:'3', text:'repayment monthly' },
  { value:'4', text:'option to pay a % in between' }
];

export const industryTypes = [
  { value:'0',  text:'Accountancy, Banking and Finance' },
  { value:'1',  text:'Advertising, Marketing and PR' },
  { value:'2',  text:'Agriculture' },
  { value:'3',  text:'Business, Consulting and Management' },
  { value:'4',  text:'Cleaning Services' },
  { value:'5',  text:'Construction' },
  { value:'6',  text:'Defence' },
  { value:'7',  text:'Engineering' },
  { value:'8',  text:'Fashion and Design' },
  { value:'9',  text:'Healthcare' },
  { value:'10', text:'Health and Beauty' },
  { value:'11', text:'Hotels and Restaurant' },
  { value:'12', text:'Information Technology' },
  { value:'13', text:'Legal Services' },
  { value:'14', text:'Manufacturing' },
  { value:'15', text:'Property and Real Estate' },
  { value:'16', text:'Publishing' },
  { value:'17', text:'Recruitment and HR' },
  { value:'18', text:'Retail and Wholesale' },
  { value:'19', text:'Sport and Leisure' },
  { value:'20', text:'Teaching and Education' },
  { value:'21', text:'Tourism' },
  { value:'22', text:'Transport' },
  { value:'23', text:'Web and Ecommerce' },
  { value:'24', text:'Other' },
];

export const businessTypes = [
  { value:'1', text:'Sole Trader' },
  { value:'2', text:'Limited Company' },
  { value:'3', text:'Limited Liability Partnership' },
  { value:'4', text:'Partnership' },
  { value:'5', text:'Society' },
  { value:'6', text:'Club' },
  { value:'7', text:'Trust' },
  { value:'8', text:'Charity' },
  { value:'9', text:'Charity (registered as limited company)' },
];

// old version
export const numberOfPeople = [
  { value:'1',  text:'1' },
  { value:'2',  text:'2' },
  { value:'3',  text:'3' },
  { value:'4',  text:'4' },
  { value:'5',  text:'5' },
  { value:'6',  text:'6' },
  { value:'7',  text:'7' },
  { value:'8',  text:'8' },
  { value:'9',  text:'9' },
  { value:'99', text:'10+' }
];
// new version
// export const numberOfPeople = [
//   { value:'1',  text:'1' },
//   { value:'2',  text:'2' },
//   { value:'3',  text:'3' },
//   { value:'4',  text:'4' },
//   { value:'99',  text:'5+' },
// ];

// export const tradingLengthTypes = [
//   { value:'1',  text:'Less than 1 Year' },
//   { value:'2',  text:'Less than 2 Years' },
//   { value:'3',  text:'Less than 5 Years' },
//   { value:'4',  text:'More than 5 Years' },
// ];

// Business/bank loan
// Family investment
// Inherited/gifted
export const fundingTypes = [
  { value:'1',  text:'Business / bank loan' },
  { value:'2',  text:'Family investment' },
  { value:'3',  text:'Inherited / gifted' },
  { value:'4',  text:'Personally funded' },
  // { value:'5',  text:'Other' },
];

export const ownershipTypes = [
  { value:'1',  text:'Owner' },
  { value:'2',  text:'Rented' },
  { value:'3',  text:'Living with Relatives' },
  // { value:'4',  text:'Other' },
];

export const bankWithTypes = [
  { value:'1',  text:'Lloyds' },
  { value:'2',  text:'Bank of Scotland' },
  { value:'3',  text:'Barclays' },
  { value:'4',  text:'Santander' },
  { value:'5',  text:'HSBC' },
  { value:'6',  text:'Natwest' },
  { value:'7',  text:'RBS' },
  { value:'8',  text:'TSB' },
  { value:'9',  text:'Other' },
];

export const numberOfTerminals = [
  { value:'1',  text:'1' },
  { value:'2',  text:'2' },
  { value:'3',  text:'3' },
  { value:'4',  text:'4' },
  { value:'5',  text:'5' },
];

export const sectorExperienceTypes= [
  { value:'1',  text:'New to the sector / field' },
  { value:'2',  text:'Some experience in this sector / field' },
  { value:'3',  text:'Previous businesses in this sector / field' },
];

// export const contractType = [
//   { value:'1',  text:'18 months duration' },
//   { value:'2',  text:'48/51 months duration' }
// ];

// export const settlementType = [
//   { value:'1',  text:'Standard (3-5 business days)' },
//   { value:'2',  text:'Faster (end of next business day)' }
// ];

// export const howTakingPayments = [
//   { value:'1',  text:'Face to Face' },
//   { value:'2',  text:'Over the Phone' },
//   { value:'3',  text:'Online' },
//   // { value:'1',  text:'Face to Face' },
//   // { value:'2',  text:'Online or Over the Phone' },
//   // { value:'3',  text:'A bit of both' }
// ];

export const agreementLengthTypes = [
  { value:'1',  text:'18 Months' },
  { value:'2',  text:'36 Months' },
  { value:'3',  text:'48 Months' },
];

export const extendedMonths = [
  { value:'1',  text:'Defer first 3 months\' charges' },
];

export const counties = [
  { value: 'Aberdeenshire', text:'Aberdeenshire' },
  { value: 'Angus', text:'Angus' },
  { value: 'Argyll & Bute', text:'Argyll & Bute' },
  { value: 'Ayrshire', text:'Ayrshire' },
  { value: 'Banffshire', text:'Banffshire' },
  { value: 'Bedfordshire', text:'Bedfordshire' },
  { value: 'Berkshire', text:'Berkshire' },
  { value: 'Berwickshire', text:'Berwickshire' },
  { value: 'Blaenau Gwent', text:'Blaenau Gwent' },
  { value: 'Borders', text:'Borders' },
  { value: 'Bridgend', text:'Bridgend' },
  { value: 'Buckinghamshire', text:'Buckinghamshire' },
  { value: 'Caithness', text:'Caithness' },
  { value: 'Caerphilly', text:'Caerphilly' },
  { value: 'Cambridgeshire', text:'Cambridgeshire' },
  { value: 'Cardiff', text:'Cardiff' },
  { value: 'Carmarthenshire', text:'Carmarthenshire' },
  { value: 'Ceredigion', text:'Ceredigion' },
  { value: 'Cheshire', text:'Cheshire' },
  { value: 'Clackmannanshire', text:'Clackmannanshire' },
  { value: 'Cleveland', text:'Cleveland' },
  { value: 'Conwy', text:'Conwy' },
  { value: 'Cornwall', text:'Cornwall' },
  { value: 'County Durham', text:'County Durham' },
  { value: 'Cumbria', text:'Cumbria' },
  { value: 'Derbyshire', text:'Derbyshire' },
  { value: 'Denbighshire', text:'Denbighshire' },
  { value: 'Devon', text:'Devon' },
  { value: 'Dorset', text:'Dorset' },
  { value: 'Dumfries & Galloway', text:'Dumfries & Galloway' },
  { value: 'Dunbartonshire', text:'Dunbartonshire' },
  { value: 'East Ayrshire', text:'East Ayrshire' },
  { value: 'East Dunbartonshire', text:'East Dunbartonshire' },
  { value: 'East Lothian', text:'East Lothian' },
  { value: 'East Renfrewshire', text:'East Renfrewshire' },
  { value: 'East Riding of Yorkshire', text:'East Riding of Yorkshire' },
  { value: 'East Sussex', text:'East Sussex' },
  { value: 'Essex', text:'Essex' },
  { value: 'Flintshire', text:'Flintshire' },
  { value: 'Gloucestershire', text:'Gloucestershire' },
  { value: 'Greater London', text:'Greater London' },
  { value: 'Greater Manchester', text:'Greater Manchester' },
  { value: 'Gwynedd', text:'Gwynedd' },
  { value: 'Fife', text:'Fife' },
  { value: 'Hampshire', text:'Hampshire' },
  { value: 'Herefordshire', text:'Herefordshire' },
  { value: 'Hertfordshire', text:'Hertfordshire' },
  { value: 'Highland', text:'Highland' },
  { value: 'Inverclyde', text:'Inverclyde' },
  { value: 'Isle of Anglesey', text:'Isle of Anglesey' },
  { value: 'Isle of Wight', text:'Isle of Wight' },
  { value: 'Isles of Scilly', text:'Isles of Scilly' },
  { value: 'Kent', text:'Kent' },
  { value: 'Kincardineshire', text:'Kincardineshire' },
  { value: 'Lanarkshire', text:'Lanarkshire' },
  { value: 'Lancashire', text:'Lancashire' },
  { value: 'Leicestershire', text:'Leicestershire' },
  { value: 'Lincolnshire', text:'Lincolnshire' },
  { value: 'Merseyside', text:'Merseyside' },
  { value: 'Merthyr Tydfil', text:'Merthyr Tydfil' },
  { value: 'Middlesex', text:'Middlesex' },
  { value: 'Midlothian', text:'Midlothian' },
  { value: 'Monmouthshire', text:'Monmouthshire' },
  { value: 'Moray', text:'Moray' },
  { value: 'Neath Port Talbot', text:'Neath Port Talbot' },
  { value: 'Newport', text:'Newport' },
  { value: 'Norfolk', text:'Norfolk' },
  { value: 'North Ayrshire', text:'North Ayrshire' },
  { value: 'North Lanarkshire', text:'North Lanarkshire' },
  { value: 'North Yorkshire', text:'North Yorkshire' },
  { value: 'Northamptonshire', text:'Northamptonshire' },
  { value: 'Northumberland', text:'Northumberland' },
  { value: 'Nottinghamshire', text:'Nottinghamshire' },
  { value: 'Orkney', text:'Orkney' },
  { value: 'Oxfordshire', text:'Oxfordshire' },
  { value: 'Pembrokeshire', text:'Pembrokeshire' },
  { value: 'Perth & Kinross', text:'Perth & Kinross' },
  { value: 'Powys', text:'Powys' },
  { value: 'Renfrewshire', text:'Renfrewshire' },
  { value: 'Rhondda Cynon Taff', text:'Rhondda Cynon Taff' },
  { value: 'Rutland', text:'Rutland' },
  { value: 'Shetland', text:'Shetland' },
  { value: 'Shropshire', text:'Shropshire' },
  { value: 'Somerset', text:'Somerset' },
  { value: 'South Ayrshire', text:'South Ayrshire' },
  { value: 'South Lanarkshire', text:'South Lanarkshire' },
  { value: 'South Yorkshire', text:'South Yorkshire' },
  { value: 'Staffordshire', text:'Staffordshire' },
  { value: 'Stirlingshire', text:'Stirlingshire' },
  { value: 'Suffolk', text:'Suffolk' },
  { value: 'Surrey', text:'Surrey' },
  { value: 'Swansea', text:'Swansea' },
  { value: 'Torfaen', text:'Torfaen' },
  { value: 'Tyne & Wear', text:'Tyne & Wear' },
  { value: 'Vale of Glamorgan', text:'Vale of Glamorgan' },
  { value: 'Warwickshire', text:'Warwickshire' },
  { value: 'West Dunbartonshire', text:'West Dunbartonshire' },
  { value: 'West Lothian', text:'West Lothian' },
  { value: 'Western Isles', text:'Western Isles' },
  { value: 'West Midlands', text:'West Midlands' },
  { value: 'West Sussex', text:'West Sussex' },
  { value: 'West Yorkshire', text:'West Yorkshire' },
  { value: 'Wiltshire', text:'Wiltshire' },
  { value: 'Worcestershire', text:'Worcestershire' },
  { value: 'Wrexham', text:'Wrexham' }
];

export const countries = [
  { value:'AF', text:'Afghanistan' },
  { value:'AX', text:'Åland Islands' },
  { value:'AL', text:'Albania' },
  { value:'DZ', text:'Algeria' },
  { value:'AS', text:'American Samoa' },
  { value:'AD', text:'Andorra' },
  { value:'AO', text:'Angola' },
  { value:'AI', text:'Anguilla' },
  { value:'AQ', text:'Antarctica' },
  { value:'AG', text:'Antigua and Barbuda' },
  { value:'AR', text:'Argentina' },
  { value:'AM', text:'Armenia' },
  { value:'AW', text:'Aruba' },
  { value:'AU', text:'Australia' },
  { value:'AT', text:'Austria' },
  { value:'AZ', text:'Azerbaijan' },
  { value:'BS', text:'Bahamas' },
  { value:'BH', text:'Bahrain' },
  { value:'BD', text:'Bangladesh' },
  { value:'BB', text:'Barbados' },
  { value:'BY', text:'Belarus' },
  { value:'BE', text:'Belgium' },
  { value:'BZ', text:'Belize' },
  { value:'BJ', text:'Benin' },
  { value:'BM', text:'Bermuda' },
  { value:'BT', text:'Bhutan' },
  { value:'BO', text:'Bolivia' },
  { value:'BA', text:'Bosnia and Herzegovina' },
  { value:'BW', text:'Botswana' },
  { value:'BV', text:'Bouvet Island' },
  { value:'BR', text:'Brazil' },
  { value:'IO', text:'British Indian Ocean Territory' },
  { value:'VG', text:'British Virgin Islands' },
  { value:'BN', text:'Brunei' },
  { value:'BG', text:'Bulgaria' },
  { value:'BF', text:'Burkina Faso' },
  { value:'MM', text:'Burma (Republic of the Union of Myanmar)' },
  { value:'BI', text:'Burundi' },
  { value:'KH', text:'Cambodia' },
  { value:'CM', text:'Cameroon' },
  { value:'CA', text:'Canada' },
  { value:'CV', text:'Cape Verde' },
  { value:'BQ', text:'Caribbean Netherlands' },
  { value:'KY', text:'Cayman Islands' },
  { value:'CF', text:'Central African Republic' },
  { value:'TD', text:'Chad' },
  { value:'CL', text:'Chile' },
  { value:'CN', text:'China' },
  { value:'CX', text:'Christmas Island' },
  { value:'CC', text:'Cocos (Keeling) Islands' },
  { value:'CO', text:'Colombia' },
  { value:'KM', text:'Comoros' },
  { value:'CG', text:'Congo (Republic of)' },
  { value:'CK', text:'Cook Islands' },
  { value:'CR', text:'Costa Rica' },
  { value:'CI', text:'Côte d’Ivoire (Ivory Coast)' },
  { value:'HR', text:'Croatia' },
  { value:'CU', text:'Cuba' },
  { value:'CW', text:'Curaçao' },
  { value:'CY', text:'Cyprus' },
  { value:'CZ', text:'Czech Republic' },
  { value:'CD', text:'Democratic Republic of the Congo' },
  { value:'DK', text:'Denmark' },
  { value:'DJ', text:'Djibouti' },
  { value:'DM', text:'Dominica' },
  { value:'DO', text:'Dominican Republic' },
  { value:'EC', text:'Ecuador' },
  { value:'EG', text:'Egypt' },
  { value:'SV', text:'El Salvador' },
  { value:'GQ', text:'Equatorial Guinea' },
  { value:'ER', text:'Eritrea' },
  { value:'EE', text:'Estonia' },
  { value:'ET', text:'Ethiopia' },
  { value:'FK', text:'Falkland Islands' },
  { value:'FO', text:'Faroe Islands' },
  { value:'FJ', text:'Fiji' },
  { value:'FI', text:'Finland' },
  { value:'FR', text:'France' },
  { value:'GF', text:'French Guiana' },
  { value:'PF', text:'French Polynesia' },
  { value:'TF', text:'French Southern Territories' },
  { value:'GA', text:'Gabon' },
  { value:'GM', text:'Gambia' },
  { value:'GE', text:'Georgia' },
  { value:'DE', text:'Germany' },
  { value:'GH', text:'Ghana' },
  { value:'GI', text:'Gibralter' },
  { value:'GR', text:'Greece' },
  { value:'GL', text:'Greenland' },
  { value:'GD', text:'Grenada' },
  { value:'GP', text:'Guadeloupe' },
  { value:'GU', text:'Guam' },
  { value:'GT', text:'Guatemala' },
  { value:'GG', text:'Guernsey' },
  { value:'GN', text:'Guinea' },
  { value:'GW', text:'Guinea-Bissau' },
  { value:'GY', text:'Guyana' },
  { value:'HT', text:'Haiti' },
  { value:'HM', text:'Heard and McDonald Islands' },
  { value:'HN', text:'Honduras' },
  { value:'HK', text:'Hong Kong' },
  { value:'HU', text:'Hungary' },
  { value:'IS', text:'Iceland' },
  { value:'IN', text:'India' },
  { value:'ID', text:'Indonesia' },
  { value:'IR', text:'Iran' },
  { value:'IQ', text:'Iraq' },
  { value:'IE', text:'Ireland' },
  { value:'IM', text:'Isle of Man' },
  { value:'IL', text:'Israel' },
  { value:'IT', text:'Italy' },
  { value:'JM', text:'Jamaica' },
  { value:'JP', text:'Japan' },
  { value:'JE', text:'Jersey' },
  { value:'JO', text:'Jordan' },
  { value:'KZ', text:'Kazakhstan' },
  { value:'KE', text:'Kenya' },
  { value:'KI', text:'Kiribati' },
  { value:'KW', text:'Kuwait' },
  { value:'KG', text:'Kyrgyzstan' },
  { value:'LA', text:'Laos' },
  { value:'LV', text:'Latvia' },
  { value:'LB', text:'Lebanon' },
  { value:'LS', text:'Lesotho' },
  { value:'LR', text:'Liberia' },
  { value:'LY', text:'Libya' },
  { value:'LI', text:'Liechtenstein' },
  { value:'LT', text:'Lithuania' },
  { value:'LU', text:'Luxembourg' },
  { value:'MO', text:'Macau' },
  { value:'MK', text:'Macedonia' },
  { value:'MG', text:'Madagascar' },
  { value:'MW', text:'Malawi' },
  { value:'MY', text:'Malaysia' },
  { value:'MV', text:'Maldives' },
  { value:'ML', text:'Mali' },
  { value:'MT', text:'Malta' },
  { value:'MH', text:'Marshall Islands' },
  { value:'MQ', text:'Martinique' },
  { value:'MR', text:'Mauritania' },
  { value:'MU', text:'Mauritius' },
  { value:'YT', text:'Mayotte' },
  { value:'MX', text:'Mexico' },
  { value:'FM', text:'Micronesia' },
  { value:'MD', text:'Moldova' },
  { value:'MC', text:'Monaco' },
  { value:'MN', text:'Mongolia' },
  { value:'ME', text:'Montenegro' },
  { value:'MS', text:'Montserrat' },
  { value:'MA', text:'Morocco' },
  { value:'MZ', text:'Mozambique' },
  { value:'NA', text:'Namibia' },
  { value:'NR', text:'Nauru' },
  { value:'NP', text:'Nepal' },
  { value:'NL', text:'Netherlands' },
  { value:'NC', text:'New Caledonia' },
  { value:'NZ', text:'New Zealand' },
  { value:'NI', text:'Nicaragua' },
  { value:'NE', text:'Niger' },
  { value:'NG', text:'Nigeria' },
  { value:'NU', text:'Niue' },
  { value:'NF', text:'Norfolk Island' },
  { value:'KP', text:'North Korea' },
  { value:'MP', text:'Northern Mariana Islands' },
  { value:'NO', text:'Norway' },
  { value:'OM', text:'Oman' },
  { value:'PK', text:'Pakistan' },
  { value:'PW', text:'Palau' },
  { value:'PS', text:'Palestine' },
  { value:'PA', text:'Panama' },
  { value:'PG', text:'Papua New Guinea' },
  { value:'PY', text:'Paraguay' },
  { value:'PE', text:'Peru' },
  { value:'PH', text:'Philippines' },
  { value:'PN', text:'Pitcairn' },
  { value:'PL', text:'Poland' },
  { value:'PT', text:'Portugal' },
  { value:'PR', text:'Puerto Rico' },
  { value:'QA', text:'Qatar' },
  { value:'RE', text:'Réunion' },
  { value:'RO', text:'Romania' },
  { value:'RU', text:'Russian Federation' },
  { value:'RW', text:'Rwanda' },
  { value:'BL', text:'Saint Barthélemy' },
  { value:'SH', text:'Saint Helena' },
  { value:'KN', text:'Saint Kitts and Nevis' },
  { value:'LC', text:'Saint Lucia' },
  { value:'MF', text:'Saint Martin (France)' },
  { value:'SX', text:'Saint Martin (Netherlands)' },
  { value:'VC', text:'Saint Vincent and Grenadines' },
  { value:'WS', text:'Samoa' },
  { value:'SM', text:'San Marino' },
  { value:'ST', text:'São Tome and Príncipe' },
  { value:'SA', text:'Saudi Arabia' },
  { value:'SN', text:'Senegal' },
  { value:'RS', text:'Serbia' },
  { value:'SC', text:'Seychelles' },
  { value:'SL', text:'Sierra Leone' },
  { value:'SG', text:'Singapore' },
  { value:'SK', text:'Slovakia' },
  { value:'SI', text:'Slovenia' },
  { value:'SB', text:'Solomon Islands' },
  { value:'SO', text:'Somalia' },
  { value:'ZA', text:'South Africa' },
  { value:'GS', text:'South Georgia and the South Sandwich Islands' },
  { value:'KR', text:'South Korea' },
  { value:'SS', text:'South Sudan' },
  { value:'ES', text:'Spain' },
  { value:'LK', text:'Sri Lanka' },
  { value:'PM', text:'St. Pierre and Miquelon' },
  { value:'SD', text:'Sudan' },
  { value:'SR', text:'Suriname' },
  { value:'SJ', text:'Svalbard and Jan Mayen Islands' },
  { value:'SZ', text:'Swaziland' },
  { value:'SE', text:'Sweden' },
  { value:'CH', text:'Switzerland' },
  { value:'SY', text:'Syria' },
  { value:'TW', text:'Taiwan' },
  { value:'TJ', text:'Tajikistan' },
  { value:'TZ', text:'Tanzania' },
  { value:'TH', text:'Thailand' },
  { value:'TL', text:'Timor-Leste' },
  { value:'TG', text:'Togo' },
  { value:'TK', text:'Tokelau' },
  { value:'TO', text:'Tonga' },
  { value:'TT', text:'Trinidad and Tobago' },
  { value:'TN', text:'Tunisia' },
  { value:'TR', text:'Turkey' },
  { value:'TM', text:'Turkmenistan' },
  { value:'TC', text:'Turks and Caicos Islands' },
  { value:'TV', text:'Tuvalu' },
  { value:'UG', text:'Uganda' },
  { value:'UA', text:'Ukraine' },
  { value:'AE', text:'United Arab Emirates' },
  { value:'GB', text:'United Kingdom' },
  { value:'UM', text:'United States Minor Outlying Islands' },
  { value:'US', text:'United States of America' },
  { value:'VI', text:'United States Virgin Islands' },
  { value:'UY', text:'Uruguay' },
  { value:'UZ', text:'Uzbekistan' },
  { value:'VU', text:'Vanuatu' },
  { value:'VA', text:'Vatican' },
  { value:'VE', text:'Venezuela' },
  { value:'VN', text:'Vietnam' },
  { value:'WF', text:'Wallis and Futuna Islands' },
  { value:'EH', text:'Western Saharan' },
  { value:'YE', text:'Yemen' },
  { value:'ZM', text:'Zambia' },
  { value:'ZW', text:'Zimbabwe' }
];

export const nationalities = [
  { value:'25', text:'British' },
  { value:'1', text:'Afghan' },
  { value:'2', text:'Albanian' },
  { value:'3', text:'Algerian' },
  { value:'4', text:'American' },
  { value:'5', text:'Andorran' },
  { value:'6', text:'Angolan' },
  { value:'7', text:'Antiguans, Barbadians' },
  { value:'8', text:'Argentine' },
  { value:'9', text:'Armenian' },
  { value:'10', text:'Australian' },
  { value:'11', text:'Austrian' },
  { value:'12', text:'Azerbaijani' },
  { value:'13', text:'Bahamian' },
  { value:'14', text:'Bahraini' },
  { value:'15', text:'Bangladeshi' },
  { value:'16', text:'Barbadian or Bajuns' },
  { value:'17', text:'Belarusian' },
  { value:'18', text:'Belgian' },
  { value:'19', text:'Belizean' },
  { value:'20', text:'Beninese' },
  { value:'21', text:'Bhutanese' },
  { value:'22', text:'Bolivian' },
  { value:'23', text:'Bosnian, Herzegovinian' },
  { value:'24', text:'Brazilian' },
  { value:'26', text:'Bruneian' },
  { value:'27', text:'Bulgarian' },
  { value:'28', text:'Burkinabe' },
  { value:'29', text:'Burmese' },
  { value:'30', text:'Burundian' },
  { value:'31', text:'Cambodian' },
  { value:'32', text:'Cameroonian' },
  { value:'33', text:'Canadian' },
  { value:'34', text:'Cape Verdian' },
  { value:'35', text:'Central African' },
  { value:'36', text:'Chadian' },
  { value:'37', text:'Chilean' },
  { value:'38', text:'Chinese' },
  { value:'39', text:'Colombian' },
  { value:'40', text:'Comoran' },
  { value:'41', text:'Congolese' },
  { value:'42', text:'Costa Rican ' },
  { value:'43', text:'Croat' },
  { value:'44', text:'Cuban' },
  { value:'45', text:'Cypriot' },
  { value:'46', text:'Czech' },
  { value:'47', text:'Dane' },
  { value:'48', text:'Djibouti' },
  { value:'49', text:'Dominican' },
  { value:'50', text:'Dominican Republic' },
  { value:'51', text:'Dutch' },
  { value:'52', text:'East Timorese' },
  { value:'53', text:'Ecuadorean' },
  { value:'54', text:'Egyptian' },
  { value:'55', text:'Emirian' },
  { value:'56', text:'Equatorial Guinean' },
  { value:'57', text:'Eritrean' },
  { value:'58', text:'Estonian' },
  { value:'59', text:'Ethiopian' },
  { value:'60', text:'Fijian' },
  { value:'61', text:'Filipino' },
  { value:'62', text:'Finn' },
  { value:'63', text:'French' },
  { value:'64', text:'Gabonese' },
  { value:'65', text:'Gambian' },
  { value:'66', text:'Georgian' },
  { value:'67', text:'German' },
  { value:'68', text:'Ghanaian' },
  { value:'69', text:'Greek' },
  { value:'70', text:'Grenadian' },
  { value:'71', text:'Guatemalan' },
  { value:'72', text:'Guinea-Bissauan' },
  { value:'73', text:'Guinean' },
  { value:'74', text:'Guyanese' },
  { value:'75', text:'Haitian' },
  { value:'76', text:'Honduran' },
  { value:'77', text:'Hungarian' },
  { value:'78', text:'I-Kirbati' },
  { value:'79', text:'Icelander' },
  { value:'80', text:'Indian' },
  { value:'81', text:'Indonesian' },
  { value:'82', text:'Iranian' },
  { value:'83', text:'Iraqi' },
  { value:'84', text:'Irish' },
  { value:'85', text:'Israeli' },
  { value:'86', text:'Italian' },
  { value:'87', text:'Ivorian' },
  { value:'88', text:'Jamaican' },
  { value:'89', text:'Japanese' },
  { value:'90', text:'Jordanian' },
  { value:'91', text:'Kazakhstani' },
  { value:'92', text:'Kenyan' },
  { value:'93', text:'Kirghiz' },
  { value:'94', text:'Kittian and Nevisian' },
  { value:'95', text:'Kuwaiti' },
  { value:'96', text:'Lao or Laotian' },
  { value:'97', text:'Latvian' },
  { value:'98', text:'Lebanese' },
  { value:'99', text:'Liberian' },
  { value:'100', text:'Libyan' },
  { value:'101', text:'Liechtensteiner' },
  { value:'102', text:'Lithuanian' },
  { value:'103', text:'Luxembourger' },
  { value:'104', text:'Macedonian' },
  { value:'105', text:'Malagasy' },
  { value:'106', text:'Malawian' },
  { value:'107', text:'Malaysian' },
  { value:'108', text:'Maldivian' },
  { value:'109', text:'Malian' },
  { value:'110', text:'Maltese' },
  { value:'111', text:'Marshallese' },
  { value:'112', text:'Mauritanian' },
  { value:'113', text:'Mauritian' },
  { value:'114', text:'Mexican' },
  { value:'115', text:'Micronesian' },
  { value:'116', text:'Moldovan' },
  { value:'117', text:'Monegasque' },
  { value:'118', text:'Mongolian' },
  { value:'119', text:'Moroccan' },
  { value:'120', text:'Mosotho' },
  { value:'121', text:'Motswana' },
  { value:'122', text:'Mozambican' },
  { value:'123', text:'Namibian' },
  { value:'124', text:'Nauruan' },
  { value:'125', text:'Nepalese' },
  { value:'126', text:'New Zealander' },
  { value:'127', text:'Ni-Vanuatu' },
  { value:'128', text:'Nicaraguan' },
  { value:'129', text:'Nigerian' },
  { value:'130', text:'North Korean' },
  { value:'131', text:'Norwegian' },
  { value:'132', text:'Omani' },
  { value:'133', text:'Pakistani' },
  { value:'134', text:'Palauan' },
  { value:'135', text:'Palestinian' },
  { value:'136', text:'Panamanian' },
  { value:'137', text:'Papua New Guinean' },
  { value:'138', text:'Paraguayan' },
  { value:'139', text:'Peruvian' },
  { value:'140', text:'Polish' },
  { value:'141', text:'Portuguese' },
  { value:'142', text:'Qatari' },
  { value:'143', text:'Romanian' },
  { value:'144', text:'Russian' },
  { value:'145', text:'Rwandan' },
  { value:'146', text:'Saint Lucian' },
  { value:'147', text:'Salvadoran' },
  { value:'148', text:'Samoan' },
  { value:'149', text:'San Marinese' },
  { value:'150', text:'Sao Tomean' },
  { value:'151', text:'Saudi Arabian' },
  { value:'152', text:'Senegalese' },
  { value:'153', text:'Serb' },
  { value:'154', text:'Seychellois' },
  { value:'155', text:'Serra Leonean' },
  { value:'156', text:'Singaporean' },
  { value:'157', text:'Slovak' },
  { value:'158', text:'Slovene' },
  { value:'159', text:'Solomon Islander' },
  { value:'160', text:'Somali' },
  { value:'161', text:'South African' },
  { value:'162', text:'South Korean' },
  { value:'163', text:'Spaniard' },
  { value:'164', text:'Sri Lanken' },
  { value:'165', text:'Sudanese' },
  { value:'166', text:'Surinamer' },
  { value:'167', text:'Swazi' },
  { value:'168', text:'Swede' },
  { value:'169', text:'Swiss' },
  { value:'170', text:'Syrian' },
  { value:'171', text:'Taiwanese' },
  { value:'172', text:'Tajik or Tadzhik' },
  { value:'173', text:'Tanzanian' },
  { value:'174', text:'Thai' },
  { value:'175', text:'Togolese' },
  { value:'176', text:'Tongan' },
  { value:'177', text:'Trinidadian or Tabagonian' },
  { value:'178', text:'Tunisian' },
  { value:'179', text:'Turk' },
  { value:'180', text:'Turkmen or Turkmens' },
  { value:'181', text:'Tuvaluan' },
  { value:'182', text:'Ugandan' },
  { value:'183', text:'Ukrainian' },
  { value:'184', text:'Uruguayan' },
  { value:'185', text:'Uzbek' },
  { value:'186', text:'Venezuelan' },
  { value:'187', text:'Vietnamese' },
  { value:'188', text:'Yemenite' },
  { value:'189', text:'Yugoslav' },
  { value:'190', text:'Zambian' },
  { value:'191', text:'Zimbabwean' }
];

export const mccCodes = [
  { value:1, text:'Accountants & Auditors', synonyms: '' },
  { value:2, text:'Adult Media, Products & Services', synonyms: '' },
  { value:3, text:'Advertising Services', synonyms: '' },
  { value:4, text:'Air-con & Refridgeration Repairs', synonyms: '' },
  { value:5, text:'Airlines', synonyms: '' },
  { value:6, text:'Alarms (No ongoing maintenance, warranties & service cotracts)', synonyms: '' },
  { value:7, text:'Bars, Pubs and Alcohol sales (Licence held and face to face only)', synonyms: '' },
  { value:8, text:'Alternative Health Practitioner', synonyms: '' },
  { value:9, text:'Ambulance Services', synonyms: 'Emergency Services' },
  { value:10, text:'Amusement Park', synonyms: 'Fair, Theme Park' },
  { value:11, text:'Antique Reproductions', synonyms: 'Store, Vintage, Boutique' },
  { value:12, text:'Antique Shops', synonyms: 'Store, Vintage, Boutique' },
  { value:13, text:'Aquariums and Seaquarium', synonyms: '' },
  { value:14, text:'Architects & Engineers', synonyms: '' },
  { value:15, text:'Art Dealer & Gallery', synonyms: '' },
  { value:16, text:'Artist Supplies', synonyms: 'Paint' },
  { value:17, text:'Auction Houses', synonyms: 'Antiques, sales' },
  { value:18, text:'Automated Gasoline Dispensers (Pay at pump)', synonyms: 'Petrol station, fuel' },
  { value:19, text:'Automobile Association', synonyms: 'Car, Motor' },
  { value:20, text:'Car & Automobile Parking', synonyms: '' },
  { value:21, text:'Automotive Accessories', synonyms: 'Car, Garage, Shop' },
  { value:22, text:'Automotive Dealer - Misc Vehicles', synonyms: 'Car, Motor' },
  { value:23, text:'Automotive Paint Shops', synonyms: 'Motor, Car, spray, garage, mechanic' },
  { value:24, text:'Automotive Repairs, Service & Valet', synonyms: 'Motor, Car, garage, mechanic, wash' },
  { value:25, text:'Automotive Supplies & Parts - New', synonyms: 'Car, Motor' },
  { value:26, text:'Automotive Top & Body Repair', synonyms: 'Motor, Car, Repair, Body shop, garage' },
  { value:27, text:'Bail Bond Payments', synonyms: '' },
  { value:28, text:'Bakers', synonyms: '' },
  { value:29, text:'Bands & Orchestras', synonyms: 'music' },
  { value:30, text:'Bathrooms - Installation & Fitting', synonyms: '' },
  { value:31, text:'Beauty Parlours & Hairdressers (Not inluding invasive treatments)', synonyms: 'Salon' },
  { value:32, text:'Betting & Gaming (Online only)', synonyms: '' },
  { value:33, text:'Betting Shops (No online gaming)', synonyms: 'Bookmaker' },
  { value:34, text:'Bicycle Shop Sales and Servicing', synonyms: 'Bike, Cycle, Repair, Shop, Store' },
  { value:35, text:'Billiard & Pool Establishments', synonyms: 'Pool, Snooker' },
  { value:36, text:'Boarding Kennels & Cattery', synonyms: 'Dog, Cat' },
  { value:37, text:'Boat Hire', synonyms: '' },
  { value:38, text:'Book Shops', synonyms: 'Literature, store' },
  { value:39, text:'Books, Periodical & Newspapers', synonyms: 'Literature, Newsagent, Shop' },
  { value:40, text:'Bowling Alley', synonyms: 'ten pin' },
  { value:41, text:'Bridal Shops', synonyms: 'Wedding' },
  { value:42, text:'Builders & General Contractors', synonyms: '' },
  { value:43, text:'Bus Lines (Including Charter)', synonyms: '' },
  { value:44, text:'Butchers', synonyms: 'Meat, Shop' },
  { value:45, text:'Cable TV Services', synonyms: '' },
  { value:46, text:'Camera & Photographic Supplies', synonyms: '' },
  { value:47, text:'Camp & Caravan Sites', synonyms: 'Outdoors' },
  { value:48, text:'Car & Truck Sales (New)', synonyms: 'Motor' },
  { value:49, text:'Car & Truck Sales (Used)', synonyms: 'Motor' },
  { value:50, text:'Car & Van Hire', synonyms: 'Motor' },
  { value:51, text:'Car Washes', synonyms: 'Salon' },
  { value:52, text:'Caravan & Trailer Sales', synonyms: '' },
  { value:53, text:'Caravan Hire', synonyms: '' },
  { value:54, text:'Carpentry', synonyms: '' },
  { value:55, text:'Carpet & Upholstery Cleaning', synonyms: '' },
  { value:56, text:'Cash & Carry - Food', synonyms: 'Shop' },
  { value:57, text:'Caterers', synonyms: 'Catering, Food' },
  { value:58, text:'Charity Shops & Donations - (Registered charity)', synonyms: '' },
  { value:59, text:'Chemicals and Allied Products', synonyms: 'Science' },
  { value:60, text:'Childcare & Nursery (all staff DBS checked)', synonyms: '' },
  { value:61, text:'Childrens wear and supplies 5641', synonyms: 'Clothes, Female, Male, Shop, store, girl, boy' },
  { value:62, text:'Chiropodists & Podiatrists (HPC registered)', synonyms: '' },
  { value:63, text:'Chiropractors (GCC registered)', synonyms: '' },
  { value:64, text:'Civic, Social & Fraternal Associations', synonyms: '' },
  { value:65, text:'Claims Management', synonyms: '' },
  { value:66, text:'Cleaning (Specialist and Sanitation)', synonyms: '' },
  { value:67, text:'Cleaning & Maintenance', synonyms: '' },
  { value:68, text:'Clothes & Costume Hire', synonyms: 'Fancy dress, Shop, Suit hire' },
  { value:69, text:'Clothing Repairs, Tailors, Seamstresses, Mending & Alteration', synonyms: '' },
  { value:70, text:'Cold Calling (phone and face 2 face)', synonyms: '' },
  { value:71, text:'College & Universities', synonyms: 'higher education, sixth form' },
  { value:72, text:'Footwear (Commercial and Leather)', synonyms: 'Shoemaker, shoes, shop, cobblers' },
  { value:73, text:'Commercial Equipment - Misc', synonyms: 'office' },
  { value:74, text:'Commercial Footwear', synonyms: 'Shoes, boots' },
  { value:75, text:'Commercial Furniture', synonyms: 'office' },
  { value:76, text:'Commercial Sports', synonyms: '' },
  { value:77, text:'Commuter Passenger Transportation', synonyms: 'trams' },
  { value:78, text:'Computer Data & Processing Services', synonyms: '' },
  { value:79, text:'Computer Maintenance, Repair & Services', synonyms: '' },
  { value:80, text:'Computer Network & Information Systems', synonyms: '' },
  { value:81, text:'Computer Sales & Peripherals', synonyms: 'Electrical, IT' },
  { value:82, text:'Computer Software Shop', synonyms: '' },
  { value:83, text:'Construction Materials', synonyms: 'Builders Yard' },
  { value:84, text:'Consumer Credit Reporting Agencies', synonyms: '' },
  { value:85, text:'Continuous Authority & Recurring Transactions (Authorisations in line with scheme rules)', synonyms: '' },
  { value:86, text:'Contractors - Decorating & General', synonyms: 'Painter, Decorator' },
  { value:87, text:'Contractors - Masonry, Plastering, Tiling & Home Repairs', synonyms: 'Painter, Decorator, stone, plasterer, tiler,' },
  { value:88, text:'Correspondence Schools', synonyms: 'Typewriting' },
  { value:89, text:'Cosmetic Shops', synonyms: 'Make up' },
  { value:90, text:'Cosmetic Surgery', synonyms: '' },
  { value:91, text:'Courier and Delivery Services', synonyms: '' },
  { value:92, text:'Court Fines', synonyms: '' },
  { value:93, text:'Currency exchange (Online)', synonyms: 'Foreign exchange' },
  { value:94, text:'Dance Halls & Studios', synonyms: 'Ballet, Dance' },
  { value:95, text:'Dating Agency (Non-escort services)', synonyms: '' },
  { value:96, text:'Debt & Parking Fines Collection (Excluding high court enforcement)', synonyms: '' },
  { value:97, text:'Debt & Parking Fine Collection (High court enforcement and `Sherrif` type operators)', synonyms: '' },
  { value:98, text:'Dentists (GDC registered)', synonyms: '' },
  { value:99, text:'Department Store', synonyms: 'Shop' },
  { value:100, text:'Detective Agencies & Security Services', synonyms: 'Private Investigator' },
  { value:101, text:'Discount Stores', synonyms: 'Shop, pound store' },
  { value:102, text:'Disinfecting & Extermination Services', synonyms: '' },
  { value:103, text:'Doctors & Physicians (GMC registered)', synonyms: 'locam' },
  { value:104, text:'Door to Door Sales', synonyms: '' },
  { value:105, text:'Double Glazing - Installation', synonyms: 'window' },
  { value:106, text:'Drapers & Window Coverings', synonyms: 'curtain, blinds' },
  { value:107, text:'Drinking Places', synonyms: 'Bar, Cocktail, Club, wine' },
  { value:108, text:'Driving Schools', synonyms: 'Lessons' },
  { value:109, text:'Chemists and Pharmacies (over the counter)', synonyms: 'Drug, Store, Pharmacy, medicine' },
  { value:110, text:'Drugs, Drug Proprieties & Sundries', synonyms: 'Chemist, Pharmacist' },
  { value:111, text:'Dry Cleaners', synonyms: '' },
  { value:112, text:'Duty Free Store', synonyms: 'Shop' },
  { value:113, text:'Electrical Parts and Equipment', synonyms: 'Shop' },
  { value:114, text:'Electrical Repair Shops', synonyms: 'Electrical, Repair' },
  { value:115, text:'Electricians', synonyms: '' },
  { value:116, text:'Electricity Board', synonyms: '' },
  { value:117, text:'Electronic Sales', synonyms: 'gadget' },
  { value:118, text:'Employment Agencies', synonyms: 'recruitment' },
  { value:119, text:'Engineers & Architects', synonyms: '' },
  { value:120, text:'Equipment Rental & Leasing', synonyms: '' },
  { value:121, text:'Family Clothing', synonyms: 'Clothes, Male, Shop, Female, childrens' },
  { value:122, text:'Fast Food Restaurant', synonyms: 'Takeaway, shop, kebab, pizza, chicken' },
  { value:123, text:'Film & Video Production (Non-adult content)', synonyms: 'Videography, Production' },
  { value:124, text:'Fireplace, Including Surrounds', synonyms: 'Wood, Coal, Burners, shop' },
  { value:125, text:'Fishmongers', synonyms: 'Shop' },
  { value:126, text:'Floor Coverings', synonyms: 'Tiles, shop, slate, ceramic, wooden, shop, carpet' },
  { value:127, text:'Florist Supplies', synonyms: 'Flowers, Shop' },
  { value:128, text:'Florists', synonyms: 'Flowers, Shop' },
  { value:129, text:'Freight - Railroad', synonyms: '' },
  { value:130, text:'Freight - Sea & Air', synonyms: '' },
  { value:131, text:'Freight - UK', synonyms: 'Lorry' },
  { value:132, text:'Fuel Distributors', synonyms: '' },
  { value:133, text:'Funeral Services & Crematoriums (No funeral plans)', synonyms: 'Undertaker' },
  { value:134, text:'Furniture', synonyms: '' },
  { value:135, text:'Furriers', synonyms: 'Fur, Skins, Animal, Natural' },
  { value:136, text:'Gas Board', synonyms: '' },
  { value:137, text:'Gift, Card and Souvenir Shops', synonyms: '' },
  { value:138, text:'Glass, Paint, Wallpaper and DIY', synonyms: 'home improvement' },
  { value:139, text:'Glassware, China & Crystal', synonyms: '' },
  { value:140, text:'Golf Courses - Public', synonyms: '' },
  { value:141, text:'Green Grocers', synonyms: 'Store, Vegetable, Fruit, Convenience' },
  { value:142, text:'Grocery Shop', synonyms: 'Store, Vegetable, Fruit, Convenience, Grocers' },
  { value:143, text:'Hardware Equipment Supplies', synonyms: 'Shop, Ironmonger' },
  { value:144, text:'Hardware Stores', synonyms: 'Shop, General, Ironmonger' },
  { value:145, text:'Health & Beauty Spa', synonyms: 'Salon, beautician' },
  { value:146, text:'Health Food Shops', synonyms: 'Nutrition, store, Natural food store' },
  { value:147, text:'Hearing Aid Sales & Repairs', synonyms: '' },
  { value:148, text:'Hire - Car & Van', synonyms: 'Motor' },
  { value:149, text:'Hire - Caravan', synonyms: 'Motor' },
  { value:150, text:'Costume & Clothing Hire', synonyms: 'Fancy dress, Shop' },
  { value:151, text:'Hire - Equipment', synonyms: '' },
  { value:152, text:'Hobby, Games & Toys', synonyms: 'Model shop, store' },
  { value:153, text:'Home Supply Warehouse Stores', synonyms: 'Shop' },
  { value:154, text:'Hospitals', synonyms: '' },
  { value:155, text:'Hotels & Guest Houses', synonyms: 'b&b' },
  { value:156, text:'Household Appliances', synonyms: 'Whitegoods, Electrical, Kitchen, Washing, Shop, Store' },
  { value:157, text:'Industrial Supplies', synonyms: 'Shop' },
  { value:158, text:'Insurance - Direct Marketing', synonyms: '' },
  { value:159, text:'Insurance - Premiums', synonyms: '' },
  { value:160, text:'Insurance - Sales & Underwriting', synonyms: '' },
  { value:161, text:'Investment Programmes & Seminars (Including land investment)', synonyms: '' },
  { value:162, text:'Jewellers', synonyms: 'Diamond, Gold, Silver, Shop, Store' },
  { value:163, text:'Kitchens - Installation & Fitting', synonyms: '' },
  { value:164, text:'Laboratory / Medical Equipment & Supplies', synonyms: '' },
  { value:165, text:'Laboratory, Medical & Dental Services', synonyms: 'Doctor' },
  { value:166, text:'Landscaping Services', synonyms: 'garden' },
  { value:167, text:'Laundry, Cleaning & Garment Services', synonyms: '' },
  { value:168, text:'Lawn and Garden Supplies Centre', synonyms: 'Shop' },
  { value:169, text:'Legal Practice (SRA registered & not principally engaged in personal bankruptcy law)', synonyms: 'Lawer, Solicitor, Barrister' },
  { value:170, text:'Loan & Credit Brokers', synonyms: '' },
  { value:171, text:'Locksmiths', synonyms: '' },
  { value:172, text:'Luggage & Handbags', synonyms: 'Bag, case' },
  { value:173, text:'Lumber and Builder Merchants', synonyms: 'Supplies, Construction, wood, DIY' },
  { value:174, text:'Management Consultancy', synonyms: '' },
  { value:175, text:'Massage Parlours (CNHC registered)', synonyms: 'Sports massage' },
  { value:176, text:'Membership Clubs', synonyms: '' },
  { value:177, text:'Membership Organisations', synonyms: 'Club' },
  { value:178, text:'Mens & Boys wear', synonyms: 'Clothes, Male, Shop' },
  { value:179, text:'Mens & Womens Clothing 5691', synonyms: 'Clothes, Female, Male, Family, Shop, store, girl, boy' },
  { value:180, text:'Metal Services and Offices', synonyms: '' },
  { value:181, text:'Miscellaneous Clothing and Accessories', synonyms: '' },
  { value:182, text:'Deli, Specialist or Miscellaneous Food Store', synonyms: 'Shop' },
  { value:183, text:'Miscellaneous Repair Shop', synonyms: '' },
  { value:184, text:'Motor Home Dealers', synonyms: 'camper' },
  { value:185, text:'Motorcycle Dealers', synonyms: 'Bike' },
  { value:186, text:'Music Shop & Instruments', synonyms: 'Store,' },
  { value:187, text:'Newsagents', synonyms: 'Shop, Convenience, newspaper stall' },
  { value:188, text:'Night Clubs (Not Lapdancing/adult)', synonyms: 'Club, Bar,' },
  { value:189, text:'Non Face to Face Sales of Tobacco, Alcohol', synonyms: 'booze, beer, shop' },
  { value:190, text:'Nursing & Personal Care Services', synonyms: '' },
  { value:191, text:'Off Licence', synonyms: 'shop, booze, store' },
  { value:192, text:'Office Equipment', synonyms: 'Shop, Printer, Store, Stationery' },
  { value:193, text:'Office Machinery', synonyms: 'Shop' },
  { value:194, text:'Office Supplies, Stationery and Copying)', synonyms: 'Shop, Photocopying' },
  { value:195, text:'Online virtual sales (Video gaming)', synonyms: '' },
  { value:196, text:'Opticians (No surgery)', synonyms: '' },
  { value:197, text:'Orthopaedic Goods', synonyms: '' },
  { value:198, text:'Osteopaths', synonyms: '' },
  { value:199, text:'Other Professional Services', synonyms: '' },
  { value:200, text:'Outbound Telemarketing Merchant', synonyms: 'Phone' },
  { value:201, text:'Paint and Varnish Supplies', synonyms: 'Shop' },
  { value:202, text:'Pawnbrokers', synonyms: '' },
  { value:203, text:'Pay Day Loans, Cheque encashment, Log book loans & Cash 4 Gold', synonyms: '' },
  { value:204, text:'Payment Faciliators', synonyms: '' },
  { value:205, text:'Peer-to-peer lending', synonyms: '' },
  { value:206, text:'Pet Shops', synonyms: 'Animal' },
  { value:207, text:'Petroleum and Associated Products', synonyms: 'Oil' },
  { value:208, text:'Photo Developers', synonyms: '' },
  { value:209, text:'Photographic Studio & Portraits', synonyms: '' },
  { value:210, text:'Physiotherapist', synonyms: '' },
  { value:211, text:'Piece Goods, Notions & Dry Goods', synonyms: '' },
  { value:212, text:'Plumbing & Heating Equipment', synonyms: '' },
  { value:213, text:'Plumbing & Heating Installation', synonyms: '' },
  { value:214, text:'Political Organisations', synonyms: 'Conservative, Labour, Green, SNP, Liberal Democrat, Party' },
  { value:215, text:'Postal Services', synonyms: 'Delivery, Courier' },
  { value:216, text:'Private Education Services', synonyms: 'Tutor, School' },
  { value:217, text:'Professional Sports Clubs', synonyms: 'Football, Rugby, Athlectics, Golf, Cricket' },
  { value:218, text:'Property Rental & Letting Agents', synonyms: '' },
  { value:219, text:'Pseudo Pharmaceuticals, Homeopathy, Legal Highs and Drug paraphemalia', synonyms: '' },
  { value:220, text:'Publishing and Printing', synonyms: '' },
  { value:221, text:'Pyramid selling / "ponzi schemes" (including chain letters)', synonyms: '' },
  { value:222, text:'Quasi Cash Merchant', synonyms: '' },
  { value:223, text:'Radio, TV & Hi-Fi Repairs', synonyms: 'Electrical, Television, Audio, Visual, Repair' },
  { value:224, text:'Re-upholsterers & Furniture Repairs', synonyms: '' },
  { value:225, text:'Record Shops', synonyms: 'Music, Store, Vinyl, CD, Tape, Sheet' },
  { value:226, text:'Religious Goods Stores', synonyms: '' },
  { value:227, text:'Religious Organisation', synonyms: 'Church, Temple, Mosque' },
  { value:228, text:'Removals', synonyms: 'Man with van' },
  { value:229, text:'Reproduction Antiques', synonyms: '' },
  { value:230, text:'Restaurants and Eating Place', synonyms: 'Café, bistro, stall, market, coffee shop, deli' },
  { value:231, text:'Roofing and Sheet Metal Supplies', synonyms: '' },
  { value:232, text:'Sale of or investment in precious metals, commodities & gems', synonyms: '' },
  { value:233, text:'Sale or supply of guns, firearms & weapons', synonyms: '' },
  { value:234, text:'Salvage Yards', synonyms: 'breaker, scrap merchants, scrap dealers, recyling centre' },
  { value:235, text:'Schools & Educational Services (Government)', synonyms: 'Education, Academy' },
  { value:236, text:'Search Engine Optimisation', synonyms: 'seo, digital marketing' },
  { value:237, text:'Security Broker & Dealers', synonyms: '' },
  { value:238, text:'Service & Petrol Stations', synonyms: 'garage, fuel' },
  { value:239, text:'Shoe Repairs', synonyms: 'Cobblers' },
  { value:240, text:'Shoe Shops', synonyms: '' },
  { value:241, text:'Snowmobile Dealers', synonyms: '' },
  { value:242, text:'Solar Panel Supply, Installation & Repair', synonyms: '' },
  { value:243, text:'Sports & Recreational Camps Membership', synonyms: '' },
  { value:244, text:'Sports & Riding Clothing', synonyms: 'Horse, Athletic, Specialist, Shop, equestrian' },
  { value:245, text:'Sports Clubs', synonyms: 'centre' },
  { value:246, text:'Sports Goods', synonyms: 'Athletic, Shop,' },
  { value:247, text:'Stamps & Coins', synonyms: '' },
  { value:248, text:'Stationery Stores 5943', synonyms: 'Shop, Business, Store' },
  { value:249, text:'Storage and Warehousing', synonyms: 'Self storage' },
  { value:250, text:'Supermarkets', synonyms: '' },
  { value:251, text:'Swimming Pools & Spas', synonyms: 'Leisure' },
  { value:252, text:'Tax Payments', synonyms: '' },
  { value:253, text:'Tax Preparation Services (CIOT registered)', synonyms: '' },
  { value:254, text:'Taxi & Limousines', synonyms: 'Limo hire' },
  { value:255, text:'Telecom Equip & Sales', synonyms: 'Phone' },
  { value:256, text:'Telecom Services', synonyms: 'Phone' },
  { value:257, text:'Telegraph Services', synonyms: '' },
  { value:258, text:'Tent, Awning & Camping Equipment', synonyms: 'Outdoors' },
  { value:259, text:'Ticket Agency & Theatre', synonyms: '' },
  { value:260, text:'Ticket Resellers & Touts', synonyms: '' },
  { value:261, text:'Timeshares', synonyms: '' },
  { value:262, text:'Tobacco, Cigarettes, Cigars, E-cigarettes Store / Stand (face to face only)', synonyms: '' },
  { value:263, text:'Tourist Attractions', synonyms: 'visitor' },
  { value:264, text:'Towing Services (Breakdown only)', synonyms: 'recovery' },
  { value:265, text:'Training - Business & Secretarial', synonyms: '' },
  { value:266, text:'Training - Vocational', synonyms: '' },
  { value:267, text:'Travel Agents & Tour Operators', synonyms: '' },
  { value:268, text:'TV & Hi-Fi Shop', synonyms: 'Electrical, Television, Audio, Visual, Projector, Store' },
  { value:269, text:'Typewriter sales, service & rental', synonyms: '' },
  { value:270, text:'Tyre Fitters', synonyms: 'Garage, Car, Truck, Wheel' },
  { value:271, text:'Petrol Stations - Elec Hot File (No pay at pump)', synonyms: 'Fuel' },
  { value:272, text:'Unaccredited private higher education institutions', synonyms: '' },
  { value:273, text:'Uniforms and Workwear', synonyms: 'Shop' },
  { value:274, text:'Second hand/ Used Merchandise Shop', synonyms: 'Store, Vintage, Boutique' },
  { value:275, text:'Value Purchase Member Financial Inst', synonyms: '' },
  { value:276, text:'Variety / Mixed Merchandise Store', synonyms: 'Shop' },
  { value:277, text:'Vets', synonyms: '' },
  { value:278, text:'Video Game Arcades', synonyms: '' },
  { value:279, text:'Video Tape Rental Shops', synonyms: 'Film, DVD, Blueray' },
  { value:280, text:'Video, Amusement & Game Supplies', synonyms: '' },
  { value:281, text:'Warranty Companies', synonyms: '' },
  { value:282, text:'Watch, Clock & Jewellery Repairs', synonyms: '' },
  { value:283, text:'Web Hosting', synonyms: 'online' },
  { value:284, text:'Welding', synonyms: '' },
  { value:285, text:'Wig Shops', synonyms: 'Hair, Store' },
  { value:286, text:'Window Cleaners', synonyms: '' },
  { value:287, text:'Wine Investment & En Primeur', synonyms: '' },
  { value:288, text:'Womens Clothing & Accessories', synonyms: 'Clothes, Female, Shop, store, girl' },
  { value:289, text:'Womens Wear', synonyms: 'Clothes, Female, Shop, store, girl' },
  { value:290, text:'Yacht Chandlers', synonyms: '' },
];