# micro site's docker-compose.yml file
version: "2"
services:
  web:
    # replace with an image we just recated and stored (in docker)
    # image: username/repository:tag
    build: .
    # volumes:
    #  - ./:/app
    ports:
      # express js port - defined n config => port 80 will work here
      - "8000:8000"
      # nodemon debug port -so we can attach VS Code to debug
      - "5858:5858"
    links:
      - mongo
  mongo:
    image: mongo
    # volumes:
    #  - /data/db:/data/db
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db
    # command: echo 'Data container for Auth_Mongo'